spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_finance_management
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10    # Maximum number of connections in the pool
      idle-timeout: 60000      # Maximum idle time for connections (in milliseconds)
      pool-name: HikariPool-1  # Name of the connection pool

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: johnny
    password: johnny
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account


